name:
  Alex Albert Desenvolvedor
description:
  Blog pessoal de estudos
url:
  https://alexalbert-dev.github.io/Compreendendo-Spring/
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/leap-day@v0.2.0
kramdown:
syntax_highlighter: 
  rouge
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
